import { useEffect, useMemo, useState } from 'react'
import { ALERTS, METRICS, SECTORS, TICKER } from './telemetryData'

function shuffled(pool) { return [...pool].sort(() => Math.random() - 0.5) }
function useCycler(pool, interval) { const [value, setValue] = useState(pool[0]); useEffect(() => { let queue = shuffled(pool); const timer = setInterval(() => { if (!queue.length) queue = shuffled(pool); setValue(queue.shift()) }, interval); return () => clearInterval(timer) }, [pool, interval]); return value }
function metricValue(metric) { const value = metric.min + Math.random() * (metric.max - metric.min); return metric.max - metric.min > 1000 ? Math.round(value).toLocaleString() : metric.max - metric.min > 10 ? value.toFixed(0) : metric.max - metric.min > 1 ? value.toFixed(1) : value.toFixed(2) }
function MetricRow({ metric }) { const [value, setValue] = useState(() => metricValue(metric)); useEffect(() => { const timer = setInterval(() => setValue(metricValue(metric)), 4200); return () => clearInterval(timer) }, [metric]); const bad = ['CRITICAL', 'DEGRADED', 'ELEVATED'].includes(metric.status); return <div className="tele-row"><span className="tele-label">{metric.label}</span><span className={`tele-value ${bad ? 'tele-bad' : ''}`}>{value}<em>{metric.unit}</em></span><span className={`tele-status ${bad ? 'tele-bad' : ''}`}>{metric.status}</span></div> }

export default function TitanTelemetry() {
  const alert = useCycler(ALERTS, 4200); const ticker = useCycler(TICKER, 6500); const [activeMetrics, setActiveMetrics] = useState(() => METRICS.slice(0, 6)); const [clock, setClock] = useState('')
  useEffect(() => { const metricTimer = setInterval(() => setActiveMetrics(shuffled(METRICS).slice(0, 6)), 9000); const clockTimer = setInterval(() => setClock(new Date().toISOString().slice(11, 19)), 1000); setClock(new Date().toISOString().slice(11, 19)); return () => { clearInterval(metricTimer); clearInterval(clockTimer) } }, [])
  const sectors = useMemo(() => SECTORS, [])
  return <div className="titan-telemetry" aria-hidden="true"><aside className="tele-panel tele-left"><header><span className="tele-dot" /><span>LIVE TELEMETRY</span><span className="tele-clock">{clock}</span></header><div className="tele-body">{activeMetrics.map((metric) => <MetricRow key={metric.label} metric={metric} />)}</div><footer><span>SOURCE: CATALYST ENGINE</span><span className="tele-blink">●</span></footer></aside><aside className="tele-panel tele-right"><header><span className="tele-dot tele-dot-alt" /><span>SECTOR STATUS</span></header><div className="tele-body">{sectors.map(([name, status]) => <div key={name} className="tele-sector"><span className="tele-label">{name}</span><span className={`tele-status tele-${status.toLowerCase()}`}>{status}</span></div>)}</div><footer><span>AAN // LIVE FEED</span><span className="tele-blink">●</span></footer></aside><div className="tele-ticker"><span className="tele-ticker-label">AAN // WIRE</span><div className="tele-ticker-scroll"><span className="tele-ticker-item" key={ticker}>{ticker}</span></div></div><div className="tele-alert"><span className="tele-alert-pip" /><span>{alert}</span></div></div>
}
